# 该文件由 CLI 自动生成，用于保存上一次确认后的配置。
LAST_CONFIG = {'project_dir': '/Users/seawaylee/app/git/tradingagent/tradingagents',
 'results_dir': './results',
 'data_cache_dir': '/Users/seawaylee/app/git/tradingagent/tradingagents/dataflows/data_cache',
 'local_data_dir': '/Users/seawaylee/app/git/tradingagent/tradingagents/local_data',
 'data_tools_cache_dir': '/Users/seawaylee/app/git/tradingagent/tradingagents/local_data/data_tools/cache',
 'data_tools_snapshot_dir': '/Users/seawaylee/app/git/tradingagent/tradingagents/local_data/data_tools/snapshots',
 'market_data_dir': '/Users/seawaylee/app/git/tradingagent/tradingagents/local_data/market_tools',
 'agent_output_dir': '/Users/seawaylee/app/git/tradingagent/tradingagents/local_data/agents',
 'backtest_output_dir': '/Users/seawaylee/app/git/tradingagent/tradingagents/local_data/backtests',
 'market_region': 'cn_a',
 'llm_provider': 'shared',
 'deep_think_llm': 'gpt-5.5',
 'quick_think_llm': 'gpt-5.5',
 'backend_url': '',
 'azure_api_version': None,
 'content_filter_max_retries': 2,
 'content_filter_skip_message': 'Skipped due to Azure content policy filter.',
 'google_thinking_level': None,
 'openai_reasoning_effort': None,
 'anthropic_effort': None,
 'internal_language': 'Chinese',
 'final_output_language': 'Chinese',
 'output_language': 'Chinese',
 'selected_analysts': ['market', 'social', 'news', 'fundamentals'],
 'research_depth': 3,
 'max_debate_rounds': 3,
 'max_risk_discuss_rounds': 3,
 'max_recur_limit': 100,
 'timeout': 180,
 'data_vendors': {'core_stock_apis': 'akshare',
                  'technical_indicators': 'akshare',
                  'fundamental_data': 'akshare',
                  'news_data': 'akshare'},
 'tool_vendors': {'get_news': 'mx,akshare',
                  'get_market_news': 'mx,akshare',
                  'get_company_announcements': 'mx,akshare',
                  'get_fundamentals': 'mx,akshare'}}
